name: Anthony Edward "Tony" Stark
species: Human
placeOfOrigin: Earth
Abilities:
  - Genius-level intellect
  - Highly proficient scientist, engineer, and businessperson
  - Expert hand-to-hand combat
  - Powered armored suit:
    - Superhuman strength and durability
    - A cyberpathic link with a prior version of his powered armored suit
